name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out
      uses: actions/checkout@v2

    - name: Build
      run: go build -v

    - name: Test
      run: |
        go test -v -bench . -race
        GOARCH=386 go test -v
